[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci'
]

[phases.build]
cmds = [
  'npm ci',
  'cd packages/database && npx prisma generate',
  'npm run build --workspace=bot'
]

[start]
cmd = 'npm run start --workspace=bot'
