[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci'
]

[phases.build]
cmds = [
  'npx prisma generate --schema=./packages/database/prisma/schema.prisma',
  'npm run build --workspace=api'
]

[start]
cmd = 'npm run start:prod --workspace=api'
